"""End-to-end corpus build: ingest -> dedup -> split -> audit -> manifest.

Run via `just data`. Writes:

  data/processed/<partition>.jsonl        gitignored, rebuilt from sources
  data/processed/corpus.manifest.json     tracked (content hashes + counts)
  docs/benchmarks/leakage-audit.md        tracked (the M3 checkpoint artifact)

Nothing under data/ except the manifest is committed (ADR-0004): the corpus
is reconstructed from its sources every time, not vendored into git.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

from .audit import leakage_audit, naive_random_split_leakage
from .dedup import find_clusters
from .ingest import load_source
from .manifest import build_manifest, write_manifest
from .schema import Row
from .sources import TIER1_SOURCES, TIER2_SOURCES
from .split import assign_partitions, partition_source_counts

DEFAULT_OUT_DIR = Path("data/processed")
DEFAULT_MANIFEST = DEFAULT_OUT_DIR / "corpus.manifest.json"
DEFAULT_AUDIT_REPORT = Path("docs/benchmarks/leakage-audit.md")


def _write_partition_jsonl(rows: list[Row], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in sorted(rows, key=lambda r: r.id):
            f.write(
                json.dumps(
                    {
                        "id": r.id,
                        "text": r.text,
                        "label": r.label,
                        "source": r.source,
                        "source_split": r.source_split,
                        "license": r.license,
                        "tier": r.tier,
                    }
                )
                + "\n"
            )


def _write_audit_report(
    path: Path,
    *,
    manifest: dict[str, Any],
    findings_summary: dict[str, int],
    naive_leakage: float,
    actual_leakage_clean: bool,
    host_note: str,
) -> None:
    lines = [
        "# Corpus split statistics and leakage audit",
        "",
        "Generated by `just data` (packages/training/.../data/pipeline.py) - do not hand-edit.",
        "",
        f"Generated: {host_note}",
        "",
        "## Partitions",
        "",
        "| partition | rows | sources |",
        "|---|---:|---|",
    ]
    partitions = manifest["partitions"]
    for name, info in partitions.items():
        src_str = ", ".join(f"{k}={v}" for k, v in info["sources"].items())
        lines.append(f"| {name} | {info['row_count']} | {src_str or '-'} |")

    lines += [
        "",
        "## Leakage remediation (this pipeline's own dedup pass)",
        "",
        f"- Cross-partition near-duplicate clusters found and remediated: "
        f"**{findings_summary['cross_split_clusters_remediated']}**",
        f"- Within-partition exact/near duplicates collapsed: "
        f"**{findings_summary['within_split_duplicates_collapsed']}**",
        f"- Rows dropped in remediation: **{findings_summary['dropped_rows']}**",
        "",
        "## Independent leakage audit (re-derived, not trusted from the splitter)",
        "",
        f"Final partitions are {'**clean**' if actual_leakage_clean else '**LEAKING**'} - "
        "no near-duplicate cluster has members in more than one partition.",
        "",
        "## Naive random-split comparison",
        "",
        "What a naive row-level 80/10/10 split (ignoring source and near-duplicate "
        "structure entirely) would have produced, computed over the same pool:",
        "",
        f"- Fraction of the naive test partition that would share a near-duplicate "
        f"cluster with something in the naive train partition: "
        f"**{naive_leakage:.1%}**",
        "- This pipeline's family-disjoint split: **0%** by construction (see audit above).",
        "",
        "This is the concrete cost of the row-level split this project's non-negotiables "
        "explicitly reject (ADR-0004): the naive number above is not hypothetical, it is "
        "measured on this exact corpus.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run(*, include_gated: bool, out_dir: Path, seed: int) -> None:
    if include_gated:
        print(
            "--include-gated was passed, but Tier-2 sources require an "
            "authenticated HF account that has accepted a click-through "
            "licence. This pipeline does not automate that; Tier-2 sources "
            "registered:",
            [s.name for s in TIER2_SOURCES],
        )

    rows_by_source: dict[str, list[Row]] = {}
    for spec in TIER1_SOURCES:
        print(f"ingesting {spec.name} ({'local' if spec.hf_id is None else spec.hf_id}) ...")
        rows_by_source[spec.name] = load_source(spec)
        print(f"  {len(rows_by_source[spec.name])} rows")

    all_rows = [r for rows in rows_by_source.values() for r in rows]
    print(f"\n{len(all_rows)} rows total across {len(rows_by_source)} sources")

    print("clustering near-duplicates (MinHash/LSH) ...")
    clusters = find_clusters(all_rows)
    n_clusters = len(set(clusters.values()))
    print(f"  {n_clusters} clusters from {len(all_rows)} rows")

    print("assigning family-disjoint partitions and remediating leakage ...")
    partitions, findings = assign_partitions(rows_by_source, clusters)
    for name, rows in partitions.items():
        print(f"  {name}: {len(rows)} rows")

    print("running independent leakage audit ...")
    report = leakage_audit(partitions, clusters)
    if not report.is_clean:
        raise RuntimeError(
            f"leakage audit FAILED after remediation: {len(report.leaking_clusters)} "
            f"clusters still span partitions - this is a bug in split.py, not data"
        )
    print("  clean: no cluster spans more than one partition")

    print("computing naive random-split comparison ...")
    naive_leakage = naive_random_split_leakage(all_rows, clusters, seed=seed)
    print(f"  naive 80/10/10 row-level split would leak {naive_leakage:.1%} of test")

    manifest = build_manifest(partitions)
    write_manifest(manifest, out_dir / "corpus.manifest.json")
    for name, rows in partitions.items():
        _write_partition_jsonl(rows, out_dir / f"{name}.jsonl")

    _write_audit_report(
        DEFAULT_AUDIT_REPORT,
        manifest=manifest,
        findings_summary={
            "cross_split_clusters_remediated": findings.cross_split_clusters_remediated,
            "within_split_duplicates_collapsed": findings.within_split_duplicates_collapsed,
            "dropped_rows": len(findings.dropped_row_ids),
        },
        naive_leakage=naive_leakage,
        actual_leakage_clean=report.is_clean,
        host_note=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    )
    print(f"\nwrote {out_dir / 'corpus.manifest.json'}")
    print(f"wrote {DEFAULT_AUDIT_REPORT}")
    print(f"\nsource breakdown per partition: {partition_source_counts(partitions)}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--include-gated", action="store_true")
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()
    run(include_gated=args.include_gated, out_dir=args.out_dir, seed=args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
