"""Apply weak multi-label supervision (labels.py) to the M3 corpus.

Reads data/processed/{train,validation}.jsonl (built by `just data`), scans
every row through the full L1 rule corpus, and writes a weak-labelled JSONL
per partition plus a coverage report. Not run on test/cross_source_eval/
hard_negatives_eval: those measure the *primary* binary detection metric and
must stay untouched by anything derived from L1, to keep L1's own eval
(Milestone 9 ablations) independent of what trained L2.

Coverage - the fraction of attack rows L1 could not place in any family and
therefore had to exclude - is printed and written to the report, because it
is not a throwaway diagnostic: it is the ceiling this label source puts on
what L2 can learn (ADR-0005).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

from portcullis.core.l0 import normalize
from portcullis.core.l1 import RuleEngine, load_rules_from_dir

from .labels import TAXONOMY, weak_label_row

DEFAULT_DATA_DIR = Path("data/processed")
DEFAULT_RULES_DIR = Path("rules")
WEAK_LABEL_PARTITIONS = ("train", "validation")


@dataclass(frozen=True, slots=True)
class _TextAndLabel:
    """Satisfies labels.LabelledText for a raw JSONL row without pulling in
    the full training.data.schema.Row (which carries fields this script
    never reads from a partition file)."""

    text: str
    label: int


def weak_label_partition(
    path: Path, engine: RuleEngine
) -> tuple[list[dict[str, object]], dict[str, int]]:
    labelled: list[dict[str, object]] = []
    stats = {"total": 0, "benign": 0, "attack_labelled": 0, "attack_excluded": 0}

    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            stats["total"] += 1

            vec = weak_label_row(_TextAndLabel(row["text"], row["label"]), engine, normalize)
            if vec is None:
                stats["attack_excluded"] += 1
                continue
            if row["label"] == 0:
                stats["benign"] += 1
            else:
                stats["attack_labelled"] += 1

            labelled.append(
                {"id": row["id"], "text": row["text"], "binary_label": row["label"], "labels": vec}
            )

    return labelled, stats


def run(*, data_dir: Path, rules_dir: Path, out_dir: Path) -> None:
    engine = RuleEngine(load_rules_from_dir(rules_dir))
    report_lines = [
        "# Weak multi-label coverage",
        "",
        "Generated by `just weak-label` "
        "(packages/training/.../l2/weak_label_corpus.py) - do not hand-edit.",
        "",
        f"Taxonomy ({len(TAXONOMY)} labels): {', '.join(TAXONOMY)}",
        "",
        "| partition | total | benign | attack, labelled | attack, excluded | exclusion rate |",
        "|---|---:|---:|---:|---:|---:|",
    ]

    for name in WEAK_LABEL_PARTITIONS:
        src = data_dir / f"{name}.jsonl"
        if not src.exists():
            raise FileNotFoundError(f"{src} missing - run `just data` first")
        labelled, stats = weak_label_partition(src, engine)

        out_path = out_dir / f"{name}.weak.jsonl"
        out_dir.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as f:
            for row in labelled:
                f.write(json.dumps(row) + "\n")

        attack_total = stats["attack_labelled"] + stats["attack_excluded"]
        excl_rate = stats["attack_excluded"] / attack_total if attack_total else 0.0
        report_lines.append(
            f"| {name} | {stats['total']} | {stats['benign']} | "
            f"{stats['attack_labelled']} | {stats['attack_excluded']} | {excl_rate:.1%} |"
        )
        print(
            f"{name}: {stats['total']} rows -> {len(labelled)} weak-labelled "
            f"({stats['attack_excluded']} attack rows excluded, {excl_rate:.1%} of attacks)"
        )

    report_lines += [
        "",
        "Excluded rows are attack-labelled by the trustworthy binary ground truth but matched "
        "no L1 rule, so no taxonomy family could be assigned without guessing. They are dropped "
        "from L2's multi-label training set entirely (ADR-0005) rather than mislabelled.",
    ]
    (Path("docs/benchmarks") / "weak-label-coverage.md").write_text(
        "\n".join(report_lines) + "\n", encoding="utf-8"
    )
    print("wrote docs/benchmarks/weak-label-coverage.md")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR)
    ap.add_argument("--rules-dir", type=Path, default=DEFAULT_RULES_DIR)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_DATA_DIR)
    args = ap.parse_args()
    run(data_dir=args.data_dir, rules_dir=args.rules_dir, out_dir=args.out_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
